const hotels = [
  {
    name: "Mandarin Oriental Guangzhou",
    url: "https://www.trip.com/hotels/guangzhou-hotel-detail-219795/mandarin-oriental-guangzhou/",
    city: "Guangzhou",
    coords: { lat: 23.119, lng: 113.322 },
    address: "Tianhe District, Guangzhou",
    ratingText: "4.9/5",
    ratingValue: 4.9,
    costHKD: 3000,
    suitableFor: ["couples", "business"] // 情侣, 商务
  },
  {
    name: "Four Seasons Hotel Guangzhou",
    url: "https://www.trip.com/hotels/guangzhou-hotel-detail-219794/four-seasons-hotel-guangzhou/",
    city: "Guangzhou",
    coords: { lat: 23.119, lng: 113.322 },
    address: "Tianhe District, Guangzhou",
    ratingText: "4.8/5",
    ratingValue: 4.8,
    costHKD: 2500,
    suitableFor: ["family", "business", "couples"] // 家庭, 商务, 情侣
  },
  {
    name: "The Ritz-Carlton Guangzhou",
    url: "https://www.trip.com/hotels/guangzhou-hotel-detail-219793/the-ritz-carlton-guangzhou/",
    city: "Guangzhou",
    coords: { lat: 23.119, lng: 113.322 },
    address: "Tianhe District, Guangzhou",
    ratingText: "4.7/5",
    ratingValue: 4.7,
    costHKD: 2200,
    suitableFor: ["business", "couples"] // 商务, 情侣
  },
  {
    name: "Legend Palace Hotel",
    url: "https://www.trip.com/hotels/macau-hotel-detail-219783/legend-palace-hotel/",
    city: "Macau",
    coords: { lat: 22.198, lng: 113.543 },
    address: "Fisherman's Wharf, Macau",
    ratingText: "5.0/5",
    ratingValue: 5.0,
    costHKD: 2400,
    suitableFor: ["family", "artistic"] // 家庭, 艺术爱好者
  },
  {
    name: "Galaxy Macau",
    url: "https://www.trip.com/hotels/macau-hotel-detail-219777/galaxy-macau/",
    city: "Macau",
    coords: { lat: 22.147, lng: 113.558 },
    address: "Cotai Strip, Macau",
    ratingText: "4.5/5",
    ratingValue: 4.5,
    costHKD: 2200,
    suitableFor: ["family", "couples", "artistic"] // 家庭, 情侣, 艺术爱好者
  },
  {
    name: "Four Seasons Hotel Shenzhen",
    url: "https://www.trip.com/hotels/shenzhen-hotel-detail-219786/four-seasons-hotel-shenzhen/",
    city: "Shenzhen",
    coords: { lat: 22.533, lng: 114.057 },
    address: "Futian District, Shenzhen",
    ratingText: "4.7/5",
    ratingValue: 4.7,
    costHKD: 2200,
    suitableFor: ["business", "couples"] // 商务, 情侣
  },
  {
    name: "The Venetian Macao",
    url: "https://www.trip.com/hotels/macau-hotel-detail-219776/the-venetian-macao/",
    city: "Macau",
    coords: { lat: 22.147, lng: 113.559 },
    address: "Cotai Strip, Macau",
    ratingText: "4.7/5",
    ratingValue: 4.7,
    costHKD: 2000,
    suitableFor: ["family", "artistic", "couples"] // 家庭, 艺术爱好者, 情侣
  },
  {
    name: "The Langham Shenzhen",
    url: "https://www.trip.com/hotels/shenzhen-hotel-detail-219791/the-langham-shenzhen/",
    city: "Shenzhen",
    coords: { lat: 22.533, lng: 114.057 },
    address: "Futian District, Shenzhen",
    ratingText: "4.7/5",
    ratingValue: 4.7,
    costHKD: 1900,
    suitableFor: ["business", "couples"] // 商务, 情侣
  },
  {
    name: "Grand Hyatt Guangzhou",
    url: "https://www.trip.com/hotels/guangzhou-hotel-detail-219796/grand-hyatt-guangzhou/",
    city: "Guangzhou",
    coords: { lat: 23.119, lng: 113.322 },
    address: "Tianhe District, Guangzhou",
    ratingText: "4.6/5",
    ratingValue: 4.6,
    costHKD: 1800,
    suitableFor: ["business", "family"] // 商务, 家庭
  },
  {
    name: "InterContinental Shenzhen",
    url: "https://www.trip.com/hotels/shenzhen-hotel-detail-219788/intercontinental-shenzhen/",
    city: "Shenzhen",
    coords: { lat: 22.533, lng: 113.973 },
    address: "Nanshan District, Shenzhen",
    ratingText: "4.6/5",
    ratingValue: 4.6,
    costHKD: 1800,
    suitableFor: ["business", "family"] // 商务, 家庭
  },
  {
    name: "Studio City Macau",
    url: "https://www.trip.com/hotels/macau-hotel-detail-219781/studio-city-macau/",
    city: "Macau",
    coords: { lat: 22.147, lng: 113.559 },
    address: "Cotai Strip, Macau",
    ratingText: "4.5/5",
    ratingValue: 4.5,
    costHKD: 1700,
    suitableFor: ["artistic", "couples", "family"] // 艺术爱好者, 情侣, 家庭
  },
  {
    name: "JW Marriott Hotel Shenzhen",
    url: "https://www.trip.com/hotels/shenzhen-hotel-detail-219790/jw-marriott-hotel-shenzhen/",
    city: "Shenzhen",
    coords: { lat: 22.533, lng: 114.057 },
    address: "Futian District, Shenzhen",
    ratingText: "4.6/5",
    ratingValue: 4.6,
    costHKD: 1700,
    suitableFor: ["business", "family"] // 商务, 家庭
  },
  {
    name: "Shangri-La Hotel Guangzhou",
    url: "https://www.trip.com/hotels/guangzhou-hotel-detail-219792/shangri-la-hotel-guangzhou/",
    city: "Guangzhou",
    coords: { lat: 23.106, lng: 113.362 },
    address: "Haizhu District, Guangzhou",
    ratingText: "4.5/5",
    ratingValue: 4.5,
    costHKD: 1600,
    suitableFor: ["family", "business"] // 家庭, 商务
  },
  {
    name: "Hilton Shenzhen Futian",
    url: "https://www.trip.com/hotels/shenzhen-hotel-detail-219789/hilton-shenzhen-futian/",
    city: "Shenzhen",
    coords: { lat: 22.533, lng: 114.057 },
    address: "Futian District, Shenzhen",
    ratingText: "4.5/5",
    ratingValue: 4.5,
    costHKD: 1600,
    suitableFor: ["business", "family"] // 商务, 家庭
  },
  {
    name: "Shangri-La Hotel Shenzhen",
    url: "https://www.trip.com/hotels/shenzhen-hotel-detail-219787/shangri-la-hotel-shenzhen/",
    city: "Shenzhen",
    coords: { lat: 22.533, lng: 114.117 },
    address: "Luohu District, Shenzhen",
    ratingText: "4.5/5",
    ratingValue: 4.5,
    costHKD: 1500,
    suitableFor: ["business", "couples"] // 商务, 情侣
  },
  {
    name: "Pullman Guangzhou Baiyun Airport",
    url: "https://www.trip.com/hotels/guangzhou-hotel-detail-219797/pullman-guangzhou-baiyun-airport/",
    city: "Guangzhou",
    coords: { lat: 23.392, lng: 113.298 },
    address: "Baiyun Airport, Guangzhou",
    ratingText: "4.5/5",
    ratingValue: 4.5,
    costHKD: 1200,
    suitableFor: ["business"] // 商务
  },
  {
    name: "St. Regis Zhuhai",
    url: "https://www.trip.com/hotels/zhuhai-hotel-detail-219799/st-regis-zhuhai/",
    city: "Zhuhai",
    coords: { lat: 22.207, lng: 113.567 },
    address: "Zhuhai",
    ratingText: "4.8/5",
    ratingValue: 4.8,
    costHKD: 1200,
    suitableFor: ["couples", "artistic"] // 情侣, 艺术爱好者
  },
  {
    name: "Hyatt Regency Zhuhai",
    url: "https://www.trip.com/hotels/zhuhai-hotel-detail-219798/hyatt-regency-zhuhai/",
    city: "Zhuhai",
    coords: { lat: 22.207, lng: 113.567 },
    address: "Zhuhai",
    ratingText: "4.6/5",
    ratingValue: 4.6,
    costHKD: 800,
    suitableFor: ["family", "business"] // 家庭, 商务
  },
  {
    name: "Hyatt Regency Dongguan",
    url: "https://www.trip.com/hotels/dongguan-hotel-detail-374631/hyatt-regency-dongguan/",
    city: "Dongguan",
    coords: { lat: 23.020, lng: 113.751 },
    address: "Songshan Lake, Dongguan",
    ratingText: "4.6/5",
    ratingValue: 4.6,
    costHKD: 800,
    suitableFor: ["business", "family"] // 商务, 家庭
  }
];